services:
  app:
    container_name: "app-dashboard"
    build: .
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - .:/code
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
#    depends_on:
#      - ollama
#      # - ollama-webui
#      - milvus
    networks:
      - ollama-docker


  attu:
    image: zilliz/attu:dev
    container_name: milvus-wedamin
    ports:
      - "9100:3000"
#    volumes:
#      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/attu:/app/tls
    environment:
      - ATTU_LOG_LEVEL=info
      - HOST_URL=http://localhost:9100
      - MILVUS_URL=http://milvus:19530
    networks:
      - ollama-docker

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "8080:8080"
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://ollama:11434 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=MY LAW AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false
  
